Tell systemd to create /run/sentry
Otherwise supervisord crashes at start:
Error: The directory named as part of the path
/run/sentry/supervisord.pid does not exist.